### ISSUE TITLE
Crash on big openapi json files

### ISSUE THREAD

**Issue by okanwyl** [alexandrehtrb/Pororoca#128]
When I try to import an openapi JSON it hangs for 5 seconds and then crashes. I'm using this [YouTrack openapi](https://youtrack.jetbrains.com/api/openapi.json)

[high-level-dump.log](https://github.com/user-attachments/files/17787187/high-level-dump.log)

**Comment by alexandrehtrb** [comment]
Hello,

Thanks for reporting this.

The bug was a recursive OpenAPI schema in the file, causing a stack overflow. A protection against that has been made and will be included in the next release. 

A side note about this file: its actions are not tagged and do not have summaries, so when they are imported by Pororoca, they will appear as a lot of `req`s. The operation tag and summary are used for folder organization and request naming, respectively. Check out the [Petstore OpenAPI](https://petstore3.swagger.io/) ([json](https://petstore3.swagger.io/api/v3/openapi.json)) to see how it works.

(You may not be the owner of the YouTrack OpenAPI, I am just explaining why importing this file will show requests in a disorganized structure.)

![Pororoca Desktop_cPiDUC6Eyp](https://github.com/user-attachments/assets/e75e5b39-5520-450d-b98a-3acc0296683b)

**Comment by okanwyl** [comment]
Hello,

Thanks for the fix and the explanation about tags/summaries. I'll check out the Petstore example. I'm closing the issue for now.
